"""add more tables

Revision ID: 69072bec7cbf
Revises: f5510ea74b1a
Create Date: 2022-07-31 13:10:13.607938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69072bec7cbf'
down_revision = 'f5510ea74b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('thrust', sa.Float(), nullable=False),
    sa.Column('power_consumption', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Integer(), nullable=False),
    sa.Column('burn_length', sa.Integer(), nullable=False),
    sa.Column('burn_length_unit', sa.String(), nullable=False),
    sa.Column('catastrophic_failure', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('energy_value', sa.Integer(), nullable=False),
    sa.Column('consumption_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ship_size', sa.Integer(), nullable=False),
    sa.Column('max_engine_size', sa.Integer(), nullable=False),
    sa.Column('min_engine_size', sa.Integer(), nullable=False),
    sa.Column('small_external_mount_points', sa.Integer(), nullable=False),
    sa.Column('medium_external_mount_points', sa.Integer(), nullable=False),
    sa.Column('large_external_mount_points', sa.Integer(), nullable=False),
    sa.Column('hull_class', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_fuel_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('fuel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engine_fuel_association')
    op.drop_table('ship_class')
    op.drop_table('fuel')
    op.drop_table('engine_failure')
    op.drop_table('engine')
    # ### end Alembic commands ###
