"""add more tables

Revision ID: f5510ea74b1a
Revises: 25e5f6c6f9ec
Create Date: 2022-07-31 13:08:08.924549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5510ea74b1a'
down_revision = '25e5f6c6f9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship')
    # ### end Alembic commands ###
